/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'validate_by_name'
  warnings.warn(message, UserWarning)
üèà Starting MLB Pre-Game Workflow Scheduler...
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 16552. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 16589. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 16642. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16551) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 16751. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Baltimore Orioles @ New York Yankees'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 17640. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 17689. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 17742. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 17816. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Chicago White Sox @ Toronto Blue Jays'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 19450. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 19488. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 19537. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 19613. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Atlanta Braves @ Miami Marlins'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 21973. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 21972. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 22037. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 22036. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 22111. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 22110. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 22315. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Cincinnati Reds @ St. Louis Cardinals'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 22316. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'New York Mets @ Philadelphia Phillies'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 44881. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 44918. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 44980. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 45044. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Milwaukee Brewers @ Minnesota Twins'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 56685. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 56732. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 56784. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 56860. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 97, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 123, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 444, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 78, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 130, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 16139) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Arizona Diamondbacks @ Colorado Rockies'[0m [36mservice[0m=[35mpre_game_workflow[0m
Exception in callback AsyncIOScheduler.shutdown(<apscheduler....t 0x10ce8ef50>, wait=True)() at /Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/apscheduler/schedulers/asyncio.py:39
handle: <Handle AsyncIOScheduler.shutdown(<apscheduler....t 0x10ce8ef50>, wait=True)() at /Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/apscheduler/schedulers/asyncio.py:39>
Traceback (most recent call last):
  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/apscheduler/schedulers/asyncio.py", line 41, in shutdown
    super().shutdown(wait)
  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 232, in shutdown
    raise SchedulerNotRunningError
apscheduler.schedulers.SchedulerNotRunningError: Scheduler is not running

============================================================
üèà MLB PRE-GAME WORKFLOW SCHEDULER
============================================================
‚è∞ Workflow Trigger: 5 minutes before each game
üåÖ Daily Setup: 06:00 EST
üìß Email Configured: ‚úÖ Yes

üìä Scheduled Games Today: 13
üí° Notifications will appear in this console

Press Ctrl+C to stop the scheduler...
============================================================


‚úÖ Pre-Game Workflow: Detroit Tigers @ Tampa Bay Rays
   Time: 19:00:15 | Status: Success
   Email: üìß Sent | Duration: 15.6s
   Workflow ID: pregame_777431_1750460400.009604

‚ùå Pre-Game Workflow: Baltimore Orioles @ New York Yankees
   Time: 19:00:18 | Status: Failed
   Email: üìß Sent | Duration: 18.6s
   Workflow ID: pregame_777438_1750460400.011273

‚ùå Pre-Game Workflow: Chicago White Sox @ Toronto Blue Jays
   Time: 19:02:17 | Status: Failed
   Email: üìß Sent | Duration: 17.5s
   Workflow ID: pregame_777435_1750460520.009115

‚ùå Pre-Game Workflow: Atlanta Braves @ Miami Marlins
   Time: 19:05:16 | Status: Failed
   Email: üìß Sent | Duration: 16.7s
   Workflow ID: pregame_777439_1750460700.008932

‚ùå Pre-Game Workflow: Cincinnati Reds @ St. Louis Cardinals
   Time: 19:10:17 | Status: Failed
   Email: üìß Sent | Duration: 17.5s
   Workflow ID: pregame_777433_1750461000.009577

‚ùå Pre-Game Workflow: New York Mets @ Philadelphia Phillies
   Time: 19:10:19 | Status: Failed
   Email: üìß Sent | Duration: 19.1s
   Workflow ID: pregame_777437_1750461000.010497

‚ùå Pre-Game Workflow: Milwaukee Brewers @ Minnesota Twins
   Time: 20:05:17 | Status: Failed
   Email: üìß Sent | Duration: 17.6s
   Workflow ID: pregame_777434_1750464300.022412

‚ùå Pre-Game Workflow: Arizona Diamondbacks @ Colorado Rockies
   Time: 20:35:18 | Status: Failed
   Email: üìß Sent | Duration: 18.2s
   Workflow ID: pregame_777430_1750466100.026919

==================================================
üìä FINAL SCHEDULER METRICS
==================================================
Scheduler Starts: 1
Daily Setups: 1
Games Scheduled: 13
Workflows Triggered: 8
Successful Workflows: 1
Failed Workflows: 7
Scheduler Errors: 0

üìà WORKFLOW METRICS:
Workflows Executed: 8
Workflows Successful: 1
Workflows Failed: 7
Stage Failures: 7
Emails Sent: 8
Success Emails Sent: 0
Failure Emails Sent: 8
Emails Deduplicated: 0
Status Change Emails Sent: 0
Total Retries: 21
Active Workflows: 0
Workflow History Count: 8
Email Configured: True
==================================================

==================================================
üìä FINAL SCHEDULER METRICS
==================================================
Scheduler Starts: 1
Daily Setups: 1
Games Scheduled: 13
Workflows Triggered: 8
Successful Workflows: 1
Failed Workflows: 7
Scheduler Errors: 0

üìà WORKFLOW METRICS:
Workflows Executed: 8
Workflows Successful: 1
Workflows Failed: 7
Stage Failures: 7
Emails Sent: 8
Success Emails Sent: 0
Failure Emails Sent: 8
Emails Deduplicated: 0
Status Change Emails Sent: 0
Total Retries: 21
Active Workflows: 0
Workflow History Count: 8
Email Configured: True
==================================================

==================================================
üìä FINAL SCHEDULER METRICS
==================================================
Scheduler Starts: 1
Daily Setups: 1
Games Scheduled: 13
Workflows Triggered: 8
Successful Workflows: 1
Failed Workflows: 7
Scheduler Errors: 0

üìà WORKFLOW METRICS:
Workflows Executed: 8
Workflows Successful: 1
Workflows Failed: 7
Stage Failures: 7
Emails Sent: 8
Success Emails Sent: 0
Failure Emails Sent: 8
Emails Deduplicated: 0
Status Change Emails Sent: 0
Total Retries: 21
Active Workflows: 0
Workflow History Count: 8
Email Configured: True
==================================================
