/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'validate_by_name'
  warnings.warn(message, UserWarning)
üèà Starting MLB Pre-Game Workflow Scheduler...
Run time of job "Daily Game Setup (trigger: cron[hour='6', minute='0'], next run at: 2025-06-20 06:00:00 EDT)" was missed by 0:16:20.523007
Run time of job "Pre-Game: Minnesota Twins @ Cincinnati Reds (trigger: date[2025-06-19 16:35:00 UTC], next run at: 2025-06-19 16:35:00 UTC)" was missed by 2:14:17.758412
Run time of job "Pre-Game: Colorado Rockies @ Washington Nationals (trigger: date[2025-06-19 17:00:00 UTC], next run at: 2025-06-19 17:00:00 UTC)" was missed by 1:49:17.763022
Run time of job "Pre-Game: Los Angeles Angels @ New York Yankees (trigger: date[2025-06-19 17:00:00 UTC], next run at: 2025-06-19 17:00:00 UTC)" was missed by 1:49:17.769294
Run time of job "Pre-Game: Pittsburgh Pirates @ Detroit Tigers (trigger: date[2025-06-19 17:05:00 UTC], next run at: 2025-06-19 17:05:00 UTC)" was missed by 1:44:17.769352
Run time of job "Pre-Game: St. Louis Cardinals @ Chicago White Sox (trigger: date[2025-06-19 18:05:00 UTC], next run at: 2025-06-19 18:05:00 UTC)" was missed by 0:44:17.769578
Run time of job "Pre-Game: St. Louis Cardinals @ Chicago White Sox (trigger: date[2025-06-19 18:10:00 UTC], next run at: 2025-06-19 18:10:00 UTC)" was missed by 0:39:17.769986
Run time of job "Pre-Game: Milwaukee Brewers @ Chicago Cubs (trigger: date[2025-06-19 18:15:00 UTC], next run at: 2025-06-19 18:15:00 UTC)" was missed by 0:34:17.770017
Run time of job "Pre-Game: Kansas City Royals @ Texas Rangers (trigger: date[2025-06-19 18:30:00 UTC], next run at: 2025-06-19 18:30:00 UTC)" was missed by 0:19:17.770240
[[31m[1merror    [0m] [1mBetting analysis failed       [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 686, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 682, in main\n    await detector.display_comprehensive_analysis(games)\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 481, in display_comprehensive_analysis\n    await self._display_no_opportunities_analysis()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 634, in _display_no_opportunities_analysis\n    await self._show_close_calls()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 657, in _show_close_calls\n    close_calls = self.db_manager.get_cursor().execute(query, (now_est, end_time)).fetchall()\nAttributeError: \'_GeneratorContextManager\' object has no attribute \'execute\'\n'[0m
[[31m[1merror    [0m] [1mBetting analysis failed       [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 686, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 682, in main\n    await detector.display_comprehensive_analysis(games)\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 481, in display_comprehensive_analysis\n    await self._display_no_opportunities_analysis()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 634, in _display_no_opportunities_analysis\n    await self._show_close_calls()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 657, in _show_close_calls\n    close_calls = self.db_manager.get_cursor().execute(query, (now_est, end_time)).fetchall()\nAttributeError: \'_GeneratorContextManager\' object has no attribute \'execute\'\n'[0m
[[31m[1merror    [0m] [1mBetting analysis failed       [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 686, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 682, in main\n    await detector.display_comprehensive_analysis(games)\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 481, in display_comprehensive_analysis\n    await self._display_no_opportunities_analysis()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 634, in _display_no_opportunities_analysis\n    await self._show_close_calls()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 657, in _show_close_calls\n    close_calls = self.db_manager.get_cursor().execute(query, (now_est, end_time)).fetchall()\nAttributeError: \'_GeneratorContextManager\' object has no attribute \'execute\'\n'[0m
[[31m[1merror    [0m] [1mBetting analysis failed       [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 686, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 682, in main\n    await detector.display_comprehensive_analysis(games)\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 481, in display_comprehensive_analysis\n    await self._display_no_opportunities_analysis()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 634, in _display_no_opportunities_analysis\n    await self._show_close_calls()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/analysis_scripts/master_betting_detector.py", line 657, in _show_close_calls\n    close_calls = self.db_manager.get_cursor().execute(query, (now_est, end_time)).fetchall()\nAttributeError: \'_GeneratorContextManager\' object has no attribute \'execute\'\n'[0m
[[31m[1merror    [0m] [1mStage betting_analysis failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Arizona Diamondbacks @ Toronto Blue Jays'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 3423. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 3454. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 3493. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 3546. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Pittsburgh Pirates @ Detroit Tigers'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 16420. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 16452. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 16497. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 16544. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Philadelphia Phillies @ Miami Marlins'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 25991. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 26023. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 26066. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 26272. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'New York Mets @ Atlanta Braves'[0m [36mservice[0m=[35mpre_game_workflow[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 30728. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 30761. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 30801. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mData collection failed        [0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mreturn_code[0m=[35m1[0m [36mservice[0m=[35mpre_game_workflow[0m [36mstderr[0m=[35m'/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'schema_extra\' has been renamed to \'json_schema_extra\'\n  warnings.warn(message, UserWarning)\n/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/.venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:\n* \'allow_population_by_field_name\' has been renamed to \'validate_by_name\'\n  warnings.warn(message, UserWarning)\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mDatabase is locked by another process. Check for stuck processes and kill them if necessary.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mCurrent process PID: 30863. Use \'ps aux | grep python | grep mlb\' to find conflicting processes.\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m\n[\x1b[31m\x1b[1merror    \x1b[0m] \x1b[1mFailed to initialize DuckDB connection\x1b[0m [\x1b[0m\x1b[1m\x1b[34mmlb_sharp_betting.db.connection\x1b[0m]\x1b[0m \x1b[36merror\x1b[0m=\x1b[35m\'Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\'\x1b[0m\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 74, in _init_connection\n    self._connection = duckdb.connect(\nduckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 96, in _init_connection\n    raise DatabaseConnectionError(\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 466, in <module>\n    asyncio.run(main()) \n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run\n    return loop.run_until_complete(main)\n  File "/Users/samlafell/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n    return future.result()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 450, in main\n    pipeline = DataPipeline(\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/entrypoint.py", line 77, in __init__\n    self.db_manager = get_db_manager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 412, in get_db_manager\n    return DatabaseManager()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 55, in __init__\n    self._init_connection()\n  File "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/src/mlb_sharp_betting/db/connection.py", line 103, in _init_connection\n    raise DatabaseConnectionError(f"Failed to initialize connection: {e}")\nmlb_sharp_betting.core.exceptions.DatabaseConnectionError: Failed to initialize connection: Database is locked by another process. Kill any stuck processes and try again: IO Error: Could not set lock on file "/Users/samlafell/Documents/programming_projects/sports_betting_dime_splits/data/raw/mlb_betting.duckdb": Conflicting lock is held in /Users/samlafell/.pyenv/versions/3.10.13/bin/python3.10 (PID 94673) by user samlafell. See also https://duckdb.org/docs/stable/connect/concurrency\n'[0m
[[31m[1merror    [0m] [1mStage data_collection failed after 3 retries[0m [[0m[1m[34mmlb_sharp_betting.services.pre_game_workflow[0m][0m [36mgame[0m=[35m'Baltimore Orioles @ Tampa Bay Rays'[0m [36mservice[0m=[35mpre_game_workflow[0m
Run time of job "Pre-Game: Houston Astros @ Athletics (trigger: date[2025-06-20 02:00:00 UTC], next run at: 2025-06-20 02:00:00 UTC)" was missed by 0:24:26.922426
Run time of job "Pre-Game: San Diego Padres @ Los Angeles Dodgers (trigger: date[2025-06-20 02:05:00 UTC], next run at: 2025-06-20 02:05:00 UTC)" was missed by 0:19:26.928419

============================================================
üèà MLB PRE-GAME WORKFLOW SCHEDULER
============================================================
‚è∞ Workflow Trigger: 5 minutes before each game
üåÖ Daily Setup: 06:00 EST
üìß Email Configured: ‚úÖ Yes

üìä Scheduled Games Today: 16
üí° Notifications will appear in this console

Press Ctrl+C to stop the scheduler...
============================================================


‚ùå Pre-Game Workflow: Arizona Diamondbacks @ Toronto Blue Jays
   Time: 15:02:24 | Status: Failed
   Email: üìß Sent | Duration: 24.8s
   Workflow ID: pregame_777448_1750359720.028574

‚úÖ Pre-Game Workflow: Cleveland Guardians @ San Francisco Giants
   Time: 16:03:37 | Status: Success
   Email: üìß Sent | Duration: 13.6s
   Workflow ID: pregame_777440_1750363403.952401

‚ùå Pre-Game Workflow: Pittsburgh Pirates @ Detroit Tigers
   Time: 17:35:32 | Status: Failed
   Email: üìß Sent | Duration: 19.3s
   Workflow ID: pregame_777464_1750368912.803792

‚ùå Pre-Game Workflow: Philadelphia Phillies @ Miami Marlins
   Time: 18:35:30 | Status: Failed
   Email: üìß Sent | Duration: 17.6s
   Workflow ID: pregame_777444_1750372513.204275

‚ùå Pre-Game Workflow: New York Mets @ Atlanta Braves
   Time: 19:12:09 | Status: Failed
   Email: üìß Sent | Duration: 17.4s
   Workflow ID: pregame_777455_1750374711.754209

‚ùå Pre-Game Workflow: Baltimore Orioles @ Tampa Bay Rays
   Time: 19:30:17 | Status: Failed
   Email: üìß Sent | Duration: 17.5s
   Workflow ID: pregame_777446_1750375800.015424

==================================================
üìä FINAL SCHEDULER METRICS
==================================================
Scheduler Starts: 1
Daily Setups: 1
Games Scheduled: 16
Workflows Triggered: 6
Successful Workflows: 1
Failed Workflows: 5
Scheduler Errors: 0

üìà WORKFLOW METRICS:
Workflows Executed: 6
Workflows Successful: 1
Workflows Failed: 5
Stage Failures: 5
Emails Sent: 6
Success Emails Sent: 0
Failure Emails Sent: 6
Emails Deduplicated: 0
Status Change Emails Sent: 0
Total Retries: 15
Active Workflows: 0
Workflow History Count: 6
Email Configured: True
==================================================

==================================================
üìä FINAL SCHEDULER METRICS
==================================================
Scheduler Starts: 1
Daily Setups: 1
Games Scheduled: 16
Workflows Triggered: 6
Successful Workflows: 1
Failed Workflows: 5
Scheduler Errors: 0

üìà WORKFLOW METRICS:
Workflows Executed: 6
Workflows Successful: 1
Workflows Failed: 5
Stage Failures: 5
Emails Sent: 6
Success Emails Sent: 0
Failure Emails Sent: 6
Emails Deduplicated: 0
Status Change Emails Sent: 0
Total Retries: 15
Active Workflows: 0
Workflow History Count: 6
Email Configured: True
==================================================
